### ISSUE TITLE
Search By Shape: Select A Layer - Drop-Down

### ISSUE THREAD

**Issue by drusexton** [tmcgee/cmv-widgets#158]
@tmcgee I only have one layer as an option to perform a selection By Shape in the Search widget. I was asked if there was anyway that I could eliminate the drop-down option. However I am not so sure you can, but I am guessing if you could it would be in the Search.html config file?

**Comment by tmcgee** [comment]
@drusexton you should not modify Search.html or any of the core files of a widget if you can avoid it. You can achieve the same results with custom CSS to hide the drop down:

``` css
.cmvSearchWidget .selectALayer {
    display: none;
}
```

Most likely, you only want to hide the drop down on the `By Shape` tab but not the `By Attribute` tab. If so, you can be more selective with your CSS selector: 

``` css
.cmvSearchWidget .searchByShape .selectALayer {
    display: none;
}
```
